from typing import Protocol
from uuid import UUID

from core.schemas import HHAccount


class ProfileServiceProtocol(Protocol):
    async def authorization_url(self, *, state: str) -> str: ...
    async def complete(self, *, user_id: UUID, code: str) -> HHAccount: ...
    async def list_accounts(self, *, user_id: UUID) -> list[HHAccount]: ...
    async def get_account(self, *, user_id: UUID, account_id: UUID) -> HHAccount | None: ...
    async def delete_account(self, *, user_id: UUID, account_id: UUID) -> None: ...
