from typing import Protocol


class SecurityProtocol(Protocol):
    def hash_password(self, password: str) -> str: ...

    def verify_password(self, password: str, password_hash: str) -> bool: ...

    def create_access_token(self, *, subject: str, session_version: int) -> str: ...

    def create_refresh_token(self, *, subject: str, session_version: int) -> str: ...

    def decode_token(self, token: str) -> dict[str, object]: ...
