from typing import Protocol
from uuid import UUID

from core.entities import Role, User


class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, *, user_id: UUID) -> User | None: ...

    async def get_by_email(self, *, email: str) -> User | None: ...

    async def create(self, *, user: User) -> User: ...

    async def get_roles(self, *, user_id: UUID) -> list[Role]: ...

    async def assign_role(self, *, user_id: UUID, role_id: UUID) -> None: ...

    async def set_active_hh_account(self, *, user_id: UUID, account_id: UUID | None) -> None: ...
